name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Smoke import src modules
        run: |
          python - <<'PY'
          from importlib import util
          import sys, os
          path = os.path.join(os.getcwd(), "src", "extract_features.py")
          spec = util.spec_from_file_location("extract_features", path)
          module = util.module_from_spec(spec)
          spec.loader.exec_module(module)
          print("imported src/extract_features.py successfully")
          PY
